PRAGMA FOREIGN_KEYS = ON;

DROP TABLE IF EXISTS SKAT_USER;
CREATE TABLE SKAT_USER
(
    Id        INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId    INTEGER NOT NULL,
    CreatedAt DATE DEFAULT CURRENT_TIMESTAMP,
    isActive  BOOLEAN
);

DROP TABLE IF EXISTS SKAT_YEAR;
CREATE TABLE SKAT_YEAR
(
    Id          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    Label       VARCHAR(225 )NOT NULL,
    CreatedAt   DATE DEFAULT (datetime('now','localtime')),
    ModifiedAt  DATE DEFAULT (datetime('now','localtime')),
    StartDate   DATE NOT NULL,
    EndDate     DATE NOT NULL
);

DROP TABLE IF EXISTS SKAT_USER_YEAR;
CREATE TABLE SKAT_USER_YEAR
(
    Id          INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    SkatUserId  INTEGER NOT NULL,
    SkatYearId  INTEGER NOT NULL,
    UserId      INTEGER NOT NULL,
    IsPaid      BOOLEAN,
    Amount      DOUBLE REAL NOT NULL,
    FOREIGN KEY(SkatUserId) REFERENCES SKAT_USER(Id) ON DELETE CASCADE,
    FOREIGN KEY(SkatYearId) REFERENCES SKAT_YEAR(Id) ON DELETE CASCADE
);